#!/bin/bash 

export CURRENT_USER=$( echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ { print $3 }' ) 
REQUIRED_COMPLIANCE_VERSION=12 
CURRENT_MACOS_VERSION=$(sudo -u "$CURRENT_USER" defaults read loginwindow SystemVersionStampAsString | cut -c1-2) 

if [ $CURRENT_MACOS_VERSION -ge $REQUIRED_COMPLIANCE_VERSION ]; then 

echo "The MacOS doesn't need any upgrade yet!" 
exit 0; 

fi 

echo "Iniciando o Processo de Upgrade" 

#### Limpeza de Disco ##### 
rm -fvR /Users/local-user01/Desktop/* 
rm -fvR /Users/CURRENT_USER/.Trash/* 
rm -fvR /Applications/MacOSBigSur.dmg 
rm -fvR /Applications/Install\ macOS\*.app 

#### Processo download, ajuste vpn e upgrade S.O #### 
softwareupdate --fetch-full-installer --full-installer-version 13.0.1

sleep 1 

killall -m Install macOS Monterey 

url_vpn_old='vpn' 
url_vpn_new='MasterOfTheUniverse' 

file_anyconnect=/Users/$CURRENT_USER/.anyconnect 
rm -fv /opt/cisco/anyconnect/profile/*.xml 
sed -i '' "s/$url_vpn_old/$url_vpn_new/g" $file_anyconnect 
echo '123Mudar$' | /Applications/Install\ macOS\ Monterey.app/Contents/Resources/startosinstall --agreetolicense --forcequitapps --stdinpass 
